In [10]:
import pandas as pd

In [11]:
csv = "Wurzburg_Weather.csv"

Wurz_df = pd.read_csv(csv, encoding="utf-8")
Wurz_df.head()

,Local time in Wurzburg,T,Po,P,Pa,U,DD,Ff,ff10,ff3,...,Cm,Ch,VV,Td,RRR,tR,E,Tg,E',sss
0,30.05.2019 23:00,15.4,745.4,769.6,NaN,68.0,Wind blowing from the west,1.0,NaN,NaN,...,NaN,NaN,70.0,9.4,NaN,NaN,NaN,NaN,NaN,NaN
1,30.05.2019 22:00,16.9,745.3,769.3,NaN,59.0,Wind blowing from the north-west,2.0,NaN,NaN,...,NaN,NaN,55.0,8.8,NaN,NaN,NaN,NaN,NaN,NaN
2,30.05.2019 21:00,18.2,745.0,768.9,NaN,53.0,Wind blowing from the north-west,3.0,NaN,NaN,...,NaN,NaN,60.0,8.5,NaN,NaN,NaN,NaN,NaN,NaN
3,30.05.2019 20:00,18.9,744.7,768.6,NaN,49.0,Wind blowing from the north-west,4.0,NaN,NaN,...,NaN,NaN,70.0,8.0,No precipitation,12.0,NaN,NaN,NaN,NaN
4,30.05.2019 19:00,19.5,744.6,768.4,NaN,47.0,Wind blowing from the west-northwest,4.0,NaN,NaN,...,NaN,NaN,70.0,7.7,NaN,NaN,NaN,NaN,NaN,NaN