In [1]:
%matplotlib inline
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os
import datetime

#wurzburg
# File to Load (Remember to change these)
wurz_flow_csv = "data/flow_wurzburg.csv"
wurz_weight_csv = "data/weight_wurzburg.csv"
wurz_temp_csv = "data/temperature_wurzburg.csv"
wurz_humid_csv = "data/humidity_wurzburg.csv"

schwa_flow_csv = "data/flow_schwartau.csv"
schwa_weight_csv = "data/weight_schwartau.csv"
schwa_temp_csv = "data/temperature_schwartau.csv"
schwa_humid_csv = "data/humidity_schwartau.csv"

# Read the hive Data
wurz_flow = pd.read_csv(wurz_flow_csv, parse_dates=['timestamp'], date_parser=pd.to_datetime)
wurz_weight = pd.read_csv(wurz_weight_csv, parse_dates=['timestamp'], date_parser=pd.to_datetime)
wurz_temp = pd.read_csv(wurz_temp_csv, parse_dates=['timestamp'], date_parser=pd.to_datetime)
wurz_humid = pd.read_csv(wurz_humid_csv, parse_dates=['timestamp'], date_parser=pd.to_datetime)

schwa_flow = pd.read_csv(schwa_flow_csv, parse_dates=['timestamp'], date_parser=pd.to_datetime)
schwa_weight = pd.read_csv(schwa_weight_csv, parse_dates=['timestamp'], date_parser=pd.to_datetime)
schwa_temp = pd.read_csv(schwa_temp_csv, parse_dates=['timestamp'], date_parser=pd.to_datetime)
schwa_humid = pd.read_csv(schwa_humid_csv, parse_dates=['timestamp'], date_parser=pd.to_datetime)

In [2]:
#Schwartau
# File to Load (Remember to change these)

schwa_flow_csv = "data/flow_schwartau.csv"
schwa_weight_csv = "data/weight_schwartau.csv"
schwa_temp_csv = "data/temperature_schwartau.csv"
schwa_humid_csv = "data/humidity_schwartau.csv"

# Read the hive Data

schwa_flow = pd.read_csv(schwa_flow_csv, parse_dates=['timestamp'], date_parser=pd.to_datetime)
schwa_weight = pd.read_csv(schwa_weight_csv, parse_dates=['timestamp'], date_parser=pd.to_datetime)
schwa_temp = pd.read_csv(schwa_temp_csv, parse_dates=['timestamp'], date_parser=pd.to_datetime)
schwa_humid = pd.read_csv(schwa_humid_csv, parse_dates=['timestamp'], date_parser=pd.to_datetime)

In [3]:
# Wurz
# add a column for day, pull the date from timestamp colummn and populate in day column in each data source used.
# also calculate the following:
# flow sum
# weight mean
# temp mean
# humid mean

pd.DatetimeIndex(wurz_flow.timestamp).normalize()
wurz_flow['day'] = pd.DatetimeIndex(wurz_flow.timestamp).normalize()
wgroup_flow = wurz_flow.groupby("day").sum()

wurz_weight['day'] = pd.DatetimeIndex(wurz_weight.timestamp).normalize()
wgroup_weight = wurz_weight.groupby("day").mean()

wurz_temp['day'] = pd.DatetimeIndex(wurz_temp.timestamp).normalize()
wgroup_temp = wurz_temp.groupby("day").mean()

wurz_humid['day'] = pd.DatetimeIndex(wurz_humid.timestamp).normalize()
wgroup_humid = wurz_humid.groupby("day").mean()

In [4]:
# Schwartau
# add a column for day, pull the date from timestamp colummn and populate in day column in each data source used.
# also calculate the following:
# flow sum
# weight mean
# temp mean
# humid mean

pd.DatetimeIndex(schwa_flow.timestamp).normalize()
schwa_flow['day'] = pd.DatetimeIndex(schwa_flow.timestamp).normalize()
sgroup_flow = schwa_flow.groupby("day").sum()

schwa_weight['day'] = pd.DatetimeIndex(schwa_weight.timestamp).normalize()
sgroup_weight = schwa_weight.groupby("day").mean()

schwa_temp['day'] = pd.DatetimeIndex(schwa_temp.timestamp).normalize()
sgroup_temp = schwa_temp.groupby("day").mean()

schwa_humid['day'] = pd.DatetimeIndex(schwa_humid.timestamp).normalize()
sgroup_humid = schwa_humid.groupby("day").mean()

In [8]:
# Wurz
# Combine the data into a single dataset

wurz_3_df = pd.merge(wgroup_humid, wgroup_temp, on="day", how="left")
wurz_2_df = pd.merge(wurz_3_df, wgroup_weight, on="day", how="left")
wurz_hive_df = pd.merge(wurz_2_df, wgroup_flow, on="day", how="left")

wurz_df = wurz_hive_df.rename(columns={"humidity":"w_humidity",
                                       "temperature":"w_temperature",
                                       "weight":"w_weight",
                                       "flow":"w_flow"})


wurz_df.head()

            w_humidity  w_temperature   w_weight  w_flow
day
2017-01-01   92.058947      -0.082160  52.661690    -6.0
2017-01-02   92.794722       1.825578  52.671111    -9.0
2017-01-03   91.173472       3.082557  52.653767    -7.0
2017-01-04   91.077917       3.750071  52.610835   -21.0
2017-01-05   82.656076       2.259225  52.623591   -12.0

In [9]:
# Schwartau
# Combine the data into a single dataset

schwa_3_df = pd.merge(sgroup_humid, sgroup_temp, on="day", how="left")
schwa_2_df = pd.merge(schwa_3_df, sgroup_weight, on="day", how="left")
schwa_hive_df = pd.merge(schwa_2_df, sgroup_flow, on="day", how="left")

schwa_df = schwa_hive_df.rename(columns={"humidity":"s_humidity",
                                       "temperature":"s_temperature",
                                       "weight":"s_weight",
                                       "flow":"s_flow"})


schwa_df.head()

            s_humidity  s_temperature      s_weight  s_flow
day
2017-01-01   98.040310      15.477829  50736.790078    -5.0
2017-01-02   98.806319      13.376389  50657.796250   -22.0
2017-01-03   98.403472      16.181965  50769.785556   -30.0
2017-01-04   97.292292      14.724111  50532.602778   -28.0
2017-01-05   96.583889       9.058442  50109.808194   -11.0

In [10]:
ws_df = pd.merge(wurz_df, schwa_df, on="day", how="left")
ws_df.head()

,w_humidity,w_temperature,w_weight,w_flow,s_humidity,s_temperature,s_weight,s_flow
day,,,,,,,,
2017-01-01,92.058947,-0.082160,52.661690,-6.0,98.040310,15.477829,50736.790078,-5.0
2017-01-02,92.794722,1.825578,52.671111,-9.0,98.806319,13.376389,50657.796250,-22.0
2017-01-03,91.173472,3.082557,52.653767,-7.0,98.403472,16.181965,50769.785556,-30.0
2017-01-04,91.077917,3.750071,52.610835,-21.0,97.292292,14.724111,50532.602778,-28.0
2017-01-05,82.656076,2.259225,52.623591,-12.0,96.583889,9.058442,50109.808194,-11.0